---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: cloudmatch-db
    name: cloudmatch-db
  name: cloudmatch-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmatch-db
  template:
    metadata:
      labels:
        app: cloudmatch-db
        actorSystemName: cloudmatch-db
    spec:
      # Termination grace period calculates as:
      # Internal shutdown timeout (10) + preStop timeout (8) + 5 seconds buffer time
      terminationGracePeriodSeconds: 23
      containers:
        - name: cloudmatch-db
          image: cloudmatch-db:1.0.0
          # Remove for a real project, the image is picked up locally for the integration test
          imagePullPolicy: Never
          ports:
            # cloudmatch db server
            - name: service
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /system/readiness
              port: service
            # It will take at least 15 seconds that the app is started. Hence, perform the first readiness check after this time.
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /system/liveness
              port: service
            # Give the app 30 seconds time to start up before performing the first liveness check.
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: cloudmatch-db-svc
spec:
  type: LoadBalancer
  selector:
    app: cloudmatch-db
  ports:
    - name: http
      protocol: TCP
      port: 81
      targetPort: 8081
